# postgresql
spring:
  datasource :
    hikari :
      maximum-pool-size : 5
    jdbc-url : jdbc:postgresql://${PSQL_URL}:${PSQL_PORT}/${PSQL_DBNAME}?currentSchema=makeboard_schema
    username : ${PSQL_USERNAME}
    password : ${PSQL_PASSWORD}
    driver-class-name : org.postgresql.Driver
    mapper-locations: classpath:/mybatis/mapper/BoardMapper.xml

  # multipart 설정
  servlet:
    multipart.max-file-size: 20MB
    max-request-size: 20MB

mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true

# swaggerdoc
springdoc:
  version: v1.0.0
  packages-to-scan: com.sideproject.makeboard
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache :
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey 적기
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey 적기
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false