# postgresql
spring:
  datasource :
    hikari :
      maximum-pool-size : 5
    jdbc-url : jdbc:postgresql://batyr.db.elephantsql.com:5432/${PSQL_USERNAME}?currentSchema=makeboard_schema
    username : ${PSQL_USERNAME}
    password : ${PSQL_PASSWORD}
    driver-class-name : org.postgresql.Driver
    mapper-locations: classpath:/mybatis/mapper/BoardMapper.xml

mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true

# swaggerdoc
springdoc:
  version: v1.0.0
  packages-to-scan: com.sideproject.makeboard
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache :
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8