# postgresql
spring:
  datasource :
    hikari :
      maximum-pool-size : 5
    jdbc-url : jdbc:postgresql://batyr.db.elephantsql.com:5432/${PSQL_USERNAME}?currentSchema=makeboard_schema
    username : ${PSQL_USERNAME}
    password : ${PSQL_PASSWORD}
    driver-class-name : org.postgresql.Driver
    mapper-locations: classpath:/mybatis/mapper/BoardMapper.xml

mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true